### ISSUE TITLE
Test Bounty

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#1]
Test.

**Comment by skylovele** [comment]
Hi @livepeer team,

I am interested in contributing to your bounty program!

About me:
- Experienced technical writer and developer
- Strong background in Python and documentation
- Active open source contributor: https://github.com/skylovele/mybook

I would like to help with documentation or beginner-friendly tasks.

Available time: 10-15 hours/week
Timeline: Flexible

Looking forward to contributing to the Livepeer ecosystem!

Best,
小 O
