### ISSUE TITLE
Make `num_inference_steps` configurable in I2I and I2V pipelines [10 LPT]

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#29]
## Overview

Currently, users can specify the `num_inference_steps` parameter in the T2I (Text-to-Image) pipeline (see the implementation [here](https://github.com/livepeer/ai-worker/blob/0a26654cccca8501bddf4e026d18cfee6c9891b2/runner/app/routes/text_to_image.py#L28)). However, this parameter is not supported in the I2I (Image-to-Image) and I2V (Image-to-Video) pipelines. We invite builders in the community to implement this functionality 🔧. By completing this bounty, you'll help enhance the flexibility and functionality of our AI pipelines, benefiting the entire community.

## Required Skillset

- Basic proficiency in [Python](https://www.python.org/).
- **Optional**: Experience with the [Hugginface diffusers library](https://huggingface.co/docs/diffusers/index).
- **Optional**: Experience with [uvicorn](https://www.uvicorn.org/) and [FastAPI](https://fastapi.tiangolo.com/) libraries.

## Bounty Requirements

**Parameter Implementation:**

* Enable users to specify the `num_inference_steps` for the I2I and I2V pipelines.

**Default Value:**

* The default `num_inference_steps` should remain the same as the current value.

**Compatibility:**

* Ensure this parameter works with all models in the I2I and I2V pipelines.

### **Reference Implementation:**

* Review the implementation of `num_inference_steps` in the T2I route and pipeline for guidance on adding this feature (see [https://github.com/livepeer/ai-worker/pull/80](https://github.com/livepeer/ai-worker/pull/80)).

### **Development Guide:**

* Consult the [AI runner development guide ](https://github.com/livepeer/ai-worker/tree/main/dev) for information on testing your implementation.

### **OpenAPI Specification:**

* After completing your implementation, run the `gen_openapi.py` file and the `make` command in the main folder to regenerate the OpenAPI spec.

## How to Apply

> [!WARNING]\
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

1. **Express Your Interest**: Comment on the issue to let us know you're interested.
2. **Wait for Review**: Our team will review expressions of interest within 14 days and select the best candidate.
3. **Get Assigned**: If selected, we'll assign the GitHub issue to you.
4. **Start Working**: Begin your work! For help or guidance, join the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our Discord server.
5. **Submit Your Work**: Create a pull request in the relevant repository and request a review.
6. **Notify Us**: Comment on the GitHub issue when your pull request is ready for review.
7. **Receive Your Bounty**: Once your pull request is approved, we'll arrange the bounty payment.
8. **Gain Recognition**: Your valuable contributions will be showcased in our [project's changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project 💛!

**Comment by tegridydev** [comment]
Interested!

**Comment by JJassonn69** [comment]
interested.

**Comment by rickstaa** [comment]
@tegridydev, @JJassonn69, thank you both for your interest in this bounty 🚀. Since @JJassonn69 has already created a pull request for this bounty (see [here](https://github.com/livepeer/ai-worker/pull/110#event-13258210876)), I have assigned the task to them.

However, @JJassonn69, please note that to qualify for the bounty reward, you must be assigned to the issue before creating a pull request. This policy helps prevent duplicate work. I have updated our documentation to emphasize this requirement. Since this was not clear in our old documentation, I will review your pull request and ensure it qualifies for the bounty.

**Comment by rickstaa** [comment]
Implemented in https://github.com/livepeer/ai-worker/pull/110#event-13258210876.

**Comment by rickstaa** [comment]
@JJassonn69 I've reviewed your bounty and successfully merged it into the codebase (see https://github.com/livepeer/ai-worker/pull/123) 🚀. Thank you so much for tackling this bounty; I believe it will significantly enhance the user experience. Please add me as a friend on Discord (@rickstaa) and DM me to claim your bounty reward 🪙.

**Comment by rickstaa** [comment]
> The Discord code you send me was cd0805c6-97ec-418c-be91-d4e5b7e7532d

Thank you for confirming. I'll go ahead and initiate the bounty transaction. 👍🏻
