### ISSUE TITLE
Research good parameters for recommended T2I models [15 LPT]

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#30]
## Overview

To give users of the AI subnet the best experience it would help to provide them a way to enable sensible defaults for our current supported pipelines and models. We invite builders in the community to research these parameters for the recommended warm models in the [T2I pipeline](https://docs.livepeer.org/ai/pipelines/text-to-image) 🔧. By completing this bounty, you'll help enhance the ease of use of the T2I pipeline, benefiting the entire community. Once we have established these defaults, we can begin implementing a way for users to apply these optimal parameters (see [LIV-471](https://linear.app/livepeer-ai/issue/LIV-471/enable-reasonable-model-defaults-in-t2i-pipeline)).

## Required Skillset

- Intermediate proficiency in [Python](https://www.python.org/).
- **Optional**: Experience with the [Hugginface diffusers library](https://huggingface.co/docs/diffusers/index).

## Bounty Requirements

The bounty requests a report provided by the bounty hunter containing the following information:

* 3 distinct prompts for which the effect of parameter ranges on image quality were tested.
* Clear visual outputs that show why a given parameter is optimal.

This information should be provided for the two **warm** models in the T2I pipeline:

* [https://huggingface.co/SG161222/RealVisXL_V4.0_Lightning](https://huggingface.co/SG161222/RealVisXL_V4.0_Lightning)
* [https://huggingface.co/ByteDance/SDXL-Lightning](https://huggingface.co/ByteDance/SDXL-Lightning)

## Implementation Tips

1. To get started checkout the hugginface page of the models. These often already apply good parameters for your parameter search.
2. To test these parameters try to abstract away the Livpeer specific code ([ai-worker](https://github.com/livepeer/ai-worker), [go-livepeer](https://github.com/livepeer/go-livepeer/tree/ai-video)) this will speedup your process. Most models provide a simple code example to perform inference for the models on your system.

## How to Apply

> [!WARNING]\
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

1. **Express Your Interest**: Comment on the issue to let us know you're interested.
2. **Wait for Review**: Our team will review expressions of interest within 14 days and select the best candidate.
3. **Get Assigned**: If selected, we'll assign the GitHub issue to you.
4. **Start Working**: Begin your work! For help or guidance, join the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our Discord server.
5. **Submit Your Work**: Create a pull request in the relevant repository and request a review.
6. **Notify Us**: Comment on the GitHub issue when your pull request is ready for review.
7. **Receive Your Bounty**: Once your pull request is approved, we'll arrange the bounty payment.
8. **Gain Recognition**: Your valuable contributions will be showcased in our [project's changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project 💛!

**Comment by papabear99** [comment]
I will write a guide with my opinions on best practices and default settings for the currently most common Livepeer AI subnet models (RealVisXL4.0_Lightning and ByteDanceSDXL_Lightning 8-step) for most images, for 0 LPT.

Short answer: (Detailed response with examples to follow soon)

For models with "Lightning" in the name, using 6-8 steps with a CFG between 2-4 will generally offer the best results in terms of image quality and speed.

For other models, 25+ steps and a CFG of 6-8 are generally optimal.

This is a complex and nuanced topic, so using a one-size-fits-all solution will undoubtedly leave some quality on the table. However, the settings above should work well for most images, balancing detail and natural appearance.

I'm off to Tahoe with the family tonight, so until later, aloha! :)

**Comment by SidereumFract** [comment]
Im interested in this bounty. I have made X/Y/X grids in the past to see how different parameters affect each other, to find good ranges of parameters. Using a static seed while varying other parameters to show the differences. As well as doing it over a range of prompts and models.

**Comment by RaghavArora14** [comment]
Hi, I'm interested in this bounty, if it's still open would love to work on this.

**Comment by rickstaa** [comment]
@SidereumFract, @RaghavArora14 Apologies for the delayed response; it seems we overlooked your messages as this bounty was already assigned to @papabear99. While the results provided by @papabear99 didn’t fully meet the bounty requirements, they were sufficient to improve our pipelines significantly. That said, we may open new research bounties in the future, so stay tuned!
