### ISSUE TITLE
Research OneDiff inference speed optimization [30 LPT]

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#31]
## Overview

Inference speed is crucial for our applications, and we aim to enhance the performance of our T2I and I2I pipelines. Previous optimizations like [DeepCache](https://github.com/horseee/DeepCache) have improved inference times but at the expense of image quality. We are interested in exploring whether another optimization, [OneDiff](https://github.com/siliconflow/onediff), can provide better results. As we are currently focused on the core AI subnet software, we are inviting community builders to conduct this research in exchange for a software bounty. If OneDiff proves effective, we will create another bounty to implement this optimization in the T2I and I2I pipelines. The successful researcher will have the first opportunity to take on this new bounty, allowing them to implement this potentially valuable feature for the community and accelerate our pipelines ⚡.

## Required Skillset

- Intermediate proficiency in [Python](https://www.python.org/).
- **Optional**: Experience with the [Hugginface diffusers library](https://huggingface.co/docs/diffusers/index).

## Bounty Requirements

* The submission must include a dedicated report outlining the inference speedup and output quality with and without the OneDiff optimization.
* The report should cover each of the models listed below in the [Text-to-Image](https://docs.livepeer.org/ai/pipelines/text-to-image) and [Image-to-Image](https://docs.livepeer.org/ai/pipelines/image-to-image) pipelines.
* Inference times should be averaged over 10 runs, and comparison images for each run should be provided.

The following items are **NOT** included in this bounty:

* This bounty does not include the [Image-to-video](https://docs.livepeer.org/ai/pipelines/image-to-video) and [upscaling](https://docs.livepeer.org/ai/pipelines/upscale) pipelines. These will be addressed in a subsequent bounty.
* This bounty is solely focused on conducting research for this optimization method. The implementation will be addressed in a subsequent bounty.

### Required models

<ins>Text-to-Image</ins>

- [SG161222/RealVisXL_V4.0_Lightning](https://huggingface.co/SG161222/RealVisXL_V4.0_Lightning)
- [SG161222/RealVisXL_V4.0](https://huggingface.co/SG161222/RealVisXL_V4.0)

<ins>Image-to-image</ins>

- [timbrooks/instruct-pix2pix](https://huggingface.co/timbrooks/instruct-pix2pix)
- [SG161222/RealVisXL_V4.0](https://huggingface.co/SG161222/RealVisXL_V4.0)

## Implementation Tips

Avoid testing OneFl directly on the [livepeer/ai-worker](https://github.com/livepeer/ai-worker) repository, as its complexity may hinder your process. Instead, create a simple inference Python script for your tests.

## How to Apply

> [!WARNING]\
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

1. **Express Your Interest**: Comment on the issue to let us know you're interested.
2. **Wait for Review**: Our team will review expressions of interest within 14 days and select the best candidate.
3. **Get Assigned**: If selected, we'll assign the GitHub issue to you.
4. **Start Working**: Begin your work! For help or guidance, join the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our Discord server.
5. **Submit Your Work**: Create a pull request in the relevant repository and request a review.
6. **Notify Us**: Comment on the GitHub issue when your pull request is ready for review.
7. **Receive Your Bounty**: Once your pull request is approved, we'll arrange the bounty payment.
8. **Gain Recognition**: Your valuable contributions will be showcased in our [project's changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project 💛!

**Comment by lukiod** [comment]
@rickstaa i am intreasted in this i request you to assign me in this .

**Comment by rickstaa** [comment]
> @rickstaa i am interested in this i request you to assign me in this .


@lukiod, thank you for your interest in implementing this bounty. I reviewed your [GitHub profile](https://github.com/tegridydev) and your experience with Python. I'm happy to announce that you are accepted to work on this bounty and qualify for the 20 LPT reward 🎉. Welcome to the Livepeer open-source community 🚀. I have provided the necessary information in this issue, but if anything is unclear, please don't hesitate to comment below or reach out in the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our [Discord server](https://discord.com/invite/livepeer).

**Comment by rickstaa** [comment]
I increased the bounty amount to 30 LPT since [due to complications](https://github.com/lukiod/T2I-and-I2I-Report/blob/main/README.md) in the OneDiff software the task took a lot longer than estimated.

**Comment by lukiod** [comment]
here is my report  https://github.com/lukiod/T2I-and-I2I-Report

**Comment by rickstaa** [comment]
> here is my report https://github.com/lukiod/T2I-and-I2I-Report

High quality report 🚀. Thanks again for your OpenSource contribution to the Livepeer ecosystem. I will contact you in DM to ensure you get your bounty reward 🪙.
