### ISSUE TITLE
Create Farcaster Livepeer T2I AI frame [125 LPT]

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#36]
## Overview

Livepeer has successfully secured the `livepeer` handle on Farcaster 🎉. With this tag now secured, we see a prime opportunity to introduce the Livepeer AI subnet to the Farcaster community. We invite builders to explore the feasibility of developing a Farcaster frame 👷, starting with an initial concept: the Livepeer AI Text-To-Image frame (view the [Figma prototype](https://www.figma.com/proto/Mvxodg40NfYTd4RjfO0h0w/Livepeer-NFT-Frame?embed_host=share&kind=proto&node-id=2-2&page-id=0%3A1&scaling=min-zoom&starting-point-node-id=2%3A2&t=ZzScUGAEz8wkCbbH-1) below).

![image](https://github.com/user-attachments/assets/ce88910b-11e0-4901-8de2-cda2c4380a6d)

By completing this bounty, you'll be featured on the Livepeer Farcaster channel and play a key role in boosting the visibility of the AI Subnet 🚀!

## Requirements

1. **Implementation Plan:**
   * Develop a detailed plan for implementing the frame, including what will be created, how it will be created, and any requirements from our side (e.g., brand assets, server to run the service on, etc.). This plan will be reviewed and refined with our guidance before implementation begins.
2. **Working Farcaster Frame:**
   * Deliver a functional Farcaster frame showcasing the Livepeer AI Text-To-Image feature.
   * Alternatively, provide a detailed guide explaining why the frame cannot currently be implemented.
3. **Open-source License:** Code should be fully open-source and released under a [MIT license](https://opensource.org/license/mit).

## Implementation Tips

* **API Reference:**
  * Review the [Livepeer API reference](https://docs.livepeer.org/ai/api-reference/text-to-image) to understand how to send a text-to-image job.
* **AI Client SDKs:**
  * Explore the experimental [Livepeer AI client SDKs](https://github.com/livepeer/livepeer-ai-sdks) to potentially accelerate your development process.
* **Beginner's Guide:**
  * Check out this [Farcaster frame building beginner's guide](https://www.youtube.com/watch?v=g_pkATT8pYU) video tutorial for foundational knowledge.
* **Documentation:**
  * Refer to the [Farcaster frames](https://docs.farcaster.xyz/learn/what-is-farcaster/frames) documentation for additional implementation details.

## How to Apply

1. **Express Your Interest**: Comment on the issue to let us know you're interested.
2. **Wait for Review**: Our team will review expressions of interest within 14 days and select the best candidate.
3. **Get Assigned**: If selected, we'll assign the GitHub issue to you.
4. **Start Working**: Begin your work! Please join the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our Discord server for assistance.
5. **Submit Your Work**: Create a pull request in the relevant repository and request a review by @KarbonDallas.
6. **Notify Us**: Comment on the GitHub issue when your pull request is ready for review.
7. **Receive Your Bounty**: Once your pull request is approved, we'll arrange the bounty payment.

Thank you for your interest in contributing to our project 💛!

> [!WARNING\]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by scapula07** [comment]
@rickstaa i am  interested

**Comment by Bruksx** [comment]
interested

**Comment by AvinashNayak27** [comment]
Hello @rickstaa,

I am interested in building the Livepeer AI Text-To-Image frame. Here are my details:

**Portfolio:** [bento.me/avinashnayak](https://bento.me/avinashnayak)
**Recent Frame I built:** [Base Colors Frame](https://warpcast.com/jake/0xb4da666b)

The frame I built involves minting a single NFT and displaying the image in the next frame, with options to share the image and mint +1 or +10 NFTs. When a user mints +10 NFTs, it shows the top collectors of the collection. The tools I used include Frog, Airstack, and Simplehash.

This bounty aligns with my expertise and interests, and I am really excited to work on this project.

Best regards,  
Avinash Nayak

**Comment by rickstaa** [comment]
Bounty applications are now closed.

Thank you, @scapula07, @Bruksx, and @AvinashNayak27, for your applications 🎉. @KarbonDallas and @rickstaa will review your profiles and select the candidate we believe is best suited for the job based on experience. We will get back to you shortly.

@Bruksx, could you please provide us with more information about why you are the right participant to tackle this bounty?

**Comment by rickstaa** [comment]
Dear @scapula07 and @AvinashNayak27,

After discussing with the team, we found both of you equally qualified for this bounty. Since @scapula07 responded earlier, we decided to assign it to them.

@AvinashNayak27, we have another Farcaster frame-related bounty which we are planning to post in the next few weeks that you could take on. Additionally, there will be many non-Farcaster bounties going live soon. Thank you for your understanding and enthusiasm 🫶.

@scapula07, @KarbonDallas will contact you shortly with the next steps for starting this bounty, including a small CLA to ensure the code is under an MIT license.

**Comment by AvinashNayak27** [comment]
Thanks for the response @rickstaa  will the next farcaster frame bounty that you are going to post will be auto assigned to me or need to re apply for it again

**Comment by rickstaa** [comment]
> Thanks for the response @rickstaa will the next farcaster frame bounty that you are going to post will be auto assigned to me or need to re apply for it again

I can auto assign it and you can decide if you want to take it on 👍🏻.

**Comment by jaylee518** [comment]
@rickstaa 
hello, is the application of this bount0y closed?

**Comment by rickstaa** [comment]
> @rickstaa hello, is the application of this bounty closed?

Hi @jaylee518, thanks for your interest in the bounty! Unfortunately, this one has already been assigned to @scapula07. However, more bounties will be posted soon, so stay tuned!

**Comment by jaylee518** [comment]
got it, thx

**Comment by AvinashNayak27** [comment]
Hey @rickstaa  any update on the frame bounty you mentioned

**Comment by jaylee518** [comment]
sorry, im not @rickstaa

**Comment by rickstaa** [comment]
> Hey @rickstaa any update on the frame bounty you mentioned

Hey @AvinashNayak27. Unfortunatelly, although this bounty has been completed already it still has not been reviewed and is not yet Live on Farcaster. After that we can see if we would like more frames. However we have a lot of other bounties comming up.

**Comment by scapula07** [comment]
@rickstaa https://github.com/scapula07/livepeer-nft-ai-frame

Link to the codebase

**Comment by scapula07** [comment]
@rickstaa hi. any update on the review of this work. its been almost 2 months since its completion and 3 months since its listing.

**Comment by rickstaa** [comment]
Implemented and paid. Will be hosted later this month.
