### ISSUE TITLE
Add parameter description to all AI endpoints [20 LPT]

### ISSUE THREAD

**Issue by rickstaa** [livepeer/bounties#40]
## Overview

> [!IMPORTANT]
> This can be viewed as a retroactive bounty. I have been in discussion with a beginner bounty hunter who asked for beginner tasks, and he already completed this task yesterday (see [here](https://github.com/livepeer/ai-worker)). Unfortunately, I didn't have time to post the bounty earlier.

The current route parameters don't have descriptions set, resulting in documentation that lacks explanations for each parameter. To fix this, we are looking for an entry-level Python programmer who can research the underlying models on Hugging Face and add descriptions to each route. This is a great first issue for anyone starting as a Livepeer Bounty Hunter 🪙⛏️ and will significantly improve the user experience of applications built on the subnet. We look forward to your submission and contributions to enhancing our documentation 🚀!

## Required Skillset

This bounty is aimed at beginner programmers with little to no experience.

## Bounty Requirements

Add descriptions for all parameters in the T2I, I2I, Upscale, I2V, and A2T pipelines. Ensure that these descriptions appear correctly in the documentation.

### Implementation Tips

All but two parameters are directly forwarded to the underlying Hugging Face diffusers pipelines. As a result, you can find the descriptions of the route parameters in the Hugging Face documentation. Here’s how to locate the relevant documentation:

1. **Identify the Route:** Go to the respective route of a given pipeline (e.g., [T2I](https://github.com/livepeer/ai-worker/blob/0e49c20fbbd5b938c3c2d96d595a7e5506d0d0ce/runner/app/routes/text_to_image.py#L27)).
2. **Locate Parameters:** The parameters are listed at the top of the [route function](https://github.com/livepeer/ai-worker/blob/0e49c20fbbd5b938c3c2d96d595a7e5506d0d0ce/runner/app/routes/text_to_image.py#L27).
3. **Find the Equivalent Pipeline:** Go to the code of the respective pipeline, focusing on the part that contains `self.ldfm` (e.g., [T2I pipeline](https://github.com/livepeer/ai-worker/blob/0e49c20fbbd5b938c3c2d96d595a7e5506d0d0ce/runner/app/pipelines/text_to_image.py#L114-L116)).
4. **Search Hugging Face:** Search for that pipeline on Hugging Face. The documentation page of the pipeline contains the parameters.

> [!NOTE]
> Some Livepeer AI pipelines use multiple Hugging Face pipelines, so please ensure you check all relevant pipelines.

### How to Apply

1. **Express Your Interest**: Comment on this issue to indicate your interest and explain why you're the ideal candidate for the task.
2. **Wait for Review**: Our team will review expressions of interest and select the best candidate.
3. **Get Assigned**: If selected, we'll assign the GitHub issue to you.
4. **Start Working**: Dive into your task! If you need assistance or guidance, comment on the issue or join the discussions in the [#🛋│developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) channel on our [Discord server](https://discord.com/invite/livepeer).
5. **Submit Your Work**: Create a pull request in the relevant repository and request a review.
6. **Notify Us**: Comment on this GitHub issue when your pull request is ready for review.
7. **Receive Your Bounty**: We'll arrange the bounty payment once your pull request is approved.
8. **Gain Recognition**: Your valuable contributions will be showcased in our [project's changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project 💛!

> [!WARNING]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by EAsuperstar** [comment]
I'll like to take on this bounty. This will provide an excellent opportunity to familiarize myself with some new concepts.

**Comment by EAsuperstar** [comment]
I have completed this bounty, please review the pull request[here](https://github.com/livepeer/ai-worker/pull/144)

**Comment by ad-astra-video** [comment]
@EAsuperstar there are a number of the descriptions that are not entirely applicable to the current implementation.

For the model_id fields, can you update the example model ids to be the default models set [here](url)?

For the input files fields (image, audio), we only support input files.  Do not support numpy arrays or tensors. Can you update to only reference a file input?

For prompts, we only accept strings, Prompt embeds, tensors or latents cannot be passed through this field.  There are also a couple other things that could be added to this description.  

- We support multiple prompts by adding a "|" to split the prompt for models that support it (SDXL-2 prompts, SD3-3 prompts).  - Can you update to include some description how prompt_embeds will be calculated in this [PR](url).  Something quick would work, like:
  - "Add '+' after word to increase weight of word in prompt or '-' to decrease the weight of the word in the prompt"

**Comment by EAsuperstar** [comment]
@ad-astra-video @rickstaa I have made changes to the descriptions as requested, see [here](https://github.com/livepeer/ai-worker/pull/144). 
I see `<gateway-ip>` listed as an important parameter for all five pipelines in the docs. This is not in the code, is this a problem? I hope not. 
Please review the file changes I have made, thanks.

**Comment by EAsuperstar** [comment]
`The Discord code you sent me to prove ownership of the GitHub account was d00c12f7-e9e4-4ced-9ca5-7e3c9cc597b3`

**Comment by rickstaa** [comment]
This was merged in https://github.com/livepeer/ai-worker/pull/144 and has been paid out on the chain already 🎉. All bounty transactions can be found back on [the AI SPE wallet](https://explorer.livepeer.org/treasury/42084921863832634370966409987770520882792921083596034115019946998721416745190). @EAsuperstar thanks a lot for improving the documentation 🚀.
