### ISSUE TITLE
Grafana Dashboard for Gateway Metrics Bounty [$500]

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/bounties#49]
# Overview

To enhance observability and performance monitoring of the AI Subnet, we are implementing a Grafana Dashboard for Gateway Metrics. This dashboard offers critical insights into the AI-job broadcasting operations performed by the Gateway, which relays AI-job requests to orchestrators across the network. [Livepeer Cloud](https://www.livepeer.cloud/) currently provides a free-to-use gateway, enabling users to test the network's capabilities. Metrics from this [pull request](https://github.com/livepeer/go-livepeer/pull/3087/) are already being collected by the public gateway and displayed on a [Grafana dashboard](https://monitor.livepeer.cloud/grafana/d/bdpyx1qkiu6tcc/ai-gateway-metrics?orgId=1&refresh=5m), accessible to the entire community. 🚀

This dashboard also provides orchestrators with an approximate view of the full network traffic, given its status as the largest gateway. Additionally, Livepeer Cloud is developing a more comprehensive system-wide metrics portal, which can be explored further [here](https://explorer.livepeer.org/treasury/69112973991711207069799657820129915730234258793790128205157315299386501373337/).

We are calling on the community to help implement this crucial part which increases the visibility of network activity. The implementation of this dashboard is crucial for monitoring and optimizing various aspects of the AI-job requests and orchestrator performance, ensuring that the ai-subnet operates efficiently and effectively. 🔥

---

## Required Skillset

- Familiarity with [Grafana](https://grafana.com/).
- Experience with [Prometheus](https://prometheus.io/) for metrics collection.

---

## Bounty Requirements

1. **Implementation:** Develop a user-friendly Grafana Dashboard that is easy to set up and tailored for `Gateways` within the network. Following create a pull request to [the Livepeer grafana dashboards repository](https://github.com/livepeer/grafana-dashboards).

3. **Functionality:** The dashboard should include the following metrics:
    - **ai_models_requested:** Number of requests per model per pipeline.
    - **ai_request_latency_score:** Latency score per pipeline to assess orchestrator performance. This metric should indicate the average time taken for a request (e.g., a 1024x1024 image with 25 time steps).
    - **ai_request_price:** The price per unit charged by orchestrators for processing jobs.
    - **ai_request_errors:** The number of errors per pipeline, providing insight into the reliability of the pipelines.
    - **Ticket_value_sent:** The value of the AI tickets sent to the Orchestrators.
    - **Tickets_send:** The total number of tickets sent to the Orchestrators.

These dashboards will provide comprehensive insights into the public gateway requests on the AI network, enabling better optimization and resource allocation.

---

## Scope Exclusions

- This bounty does **NOT** cover the addition of new metrics such as `livepeer_current_ai_sessions_total`. These additional metrics can be considered in a future bounty.

---

## Implementation Tips

To understand how to work with Gateway metrics, you can refer to a recent pull request that deals with related functionality:

 [Pull Request #3087](https://github.com/livepeer/go-livepeer/pull/3087/)

Additionally, make sure to:

- **Leverage Existing Metrics:** Review existing metrics related to AI requests on the Gateway, which are already implemented on the Cloud Gateway [Dashboard](https://monitor.livepeer.cloud/grafana/d/bdpyx1qkiu6tcc/ai-gateway-metrics?orgId=1&refresh=5m/). This will provide an initial template for a starting point.
- **Utilize Documentation:** Check out  [livepeer forum](https://forum.livepeer.org/t/guide-transcoder-monitoring-with-prometheus-grafana/1225/) for basic instructions on how to get started.

---

## How to Apply

1. **Express Your Interest:** Comment on this issue to indicate your interest and explain why you're the ideal candidate for the task.
2. **Wait for Review:** Our team will review expressions of interest and select the best candidate.
4. **Get Assigned:** If selected, we'll assign the GitHub issue to you.
5. **Start Working:** Dive into your task! If you need assistance or guidance, comment on the issue or join the discussions in the `#developer-lounge` channel on our [Discord server](https://discord.gg/livepeer).
6. **Submit Your Work:** Create a pull request in the relevant repository and request a review.
7. **Notify Us:** Comment on this GitHub issue when your pull request is ready for review.
8. **Receive Your Bounty:** We'll arrange the bounty payment once your pull request is approved.
9. **Gain Recognition:** Your valuable contributions will be showcased in our project's [changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project! 💛

> [!WARNING]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by rickstaa** [comment]
This was implemented by @stronk-dev in https://github.com/livepeer/grafana-dashboards/pull/1 🚀.

**Comment by stronk-dev** [comment]
> This was implemented by @stronk-dev in [livepeer/grafana-dashboards#1](https://github.com/livepeer/grafana-dashboards/pull/1) 🙏🏻.

Not quite - the dashboard I published is for node operators. For gateways we'll want to omit machine and probably stick to more detailed panels for pipelines/models. They'll certainly have some shared panels

**Comment by rickstaa** [comment]
This was completed and paid out. Thanks @stronk-dev for your contribution ❤️.
