### ISSUE TITLE
Grafana Dashboard for Orchestrator Metrics Bounty [$500]

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/bounties#50]
# Overview

To bolster observability and performance monitoring within the Livepeer `AI network`, we want to develop a Grafana Dashboard focused on `Orchestrator` Metrics. This dashboard will deliver vital insights into the AI-job operations managed by Orchestrators, empowering them with approximate health metrics of their servers. By offering a comparative analysis of their operations against others in the network, orchestrators will gain the tools needed to optimize their nodes and secure more work opportunities. 🚀

We invite the community to contribute to this essential initiative, which will significantly enhance orchestrator operations and visibility. The implementation of this dashboard is key to monitoring and optimizing AI job requests and orchestrator performance, ensuring the AI subnet operates at peak efficiency. 🔥

---

## Required Skillset

- Familiarity with [Grafana](https://grafana.com/).
- Experience with [Prometheus](https://prometheus.io/) for metrics collection.

---

## Bounty Requirements

Several orchestrator-specific metrics have been added to the `ai-video` branch through [this pull request](https://github.com/livepeer/go-livepeer/pull/3097). Leveraging these metrics, the bounty hunter is expected to:

1. **Implementation:** Develop a user-friendly Grafana Dashboard that is easy to set up and tailored for `Orchestrators` within the network. Following create a pull request to [the Livepeer grafana dashboards repository](https://github.com/livepeer/grafana-dashboards).
2. **Functionality:** The dashboard should showcase essential metrics such as `number of requests per model and pipeline`, `price per unit paid per request`, `request latency score`, `error rates`, `estimated inference earnings`, `total tickets received`, `winning tickets`, and other critical data points.

## Scope Exclusions

---

## Scope Exclusions

- This bounty does **NOT** cover the addition of new metrics like `livepeer_current_ai_sessions_total`. These additional metrics can be considered in a future bounty.

---

## Implementation Tips

To understand how to work with `Orchestrator` metrics, you can refer to a recent pull request that is similar and deals with metrics for Gateway operators.

 [Pull Request #3087](https://github.com/livepeer/go-livepeer/pull/3087/)

Additionally, make sure to:

- **Leverage Existing Metrics:** Review existing metrics related to AI requests on the Gateway side, which are already implemented on the Cloud Gateway [Dashboard](https://monitor.livepeer.cloud/grafana/d/bdpyx1qkiu6tcc/ai-gateway-metrics?orgId=1&refresh=5m/). This will provide an initial template for a starting point.
- **Utilize Documentation:** Check out  [livepeer forum](https://forum.livepeer.org/t/guide-transcoder-monitoring-with-prometheus-grafana/1225/) for basic instructions on how to get started setting up the `prometheus` and `grafana`.

---

## How to Apply

1. **Express Your Interest:** Comment on this issue to indicate your interest and explain why you're the ideal candidate for the task.
2. **Wait for Review:** Our team will review expressions of interest and select the best candidate.
4. **Get Assigned:** If selected, we'll assign the GitHub issue to you.
5. **Start Working:** Dive into your task! If you need assistance or guidance, comment on the issue or join the discussions in the `#developer-lounge` channel on our [Discord server](https://discord.gg/livepeer).
6. **Submit Your Work:** Create a pull request in the relevant repository and request a review.
7. **Notify Us:** Comment on this GitHub issue when your pull request is ready for review.
8. **Receive Your Bounty:** We'll arrange the bounty payment once your pull request is approved.
9. **Gain Recognition:** Your valuable contributions will be showcased in our project's [changelog](https://livepeer-ai.productlane.com/changelog).

Thank you for your interest in contributing to our project! 💛

> [!WARNING]
> Please wait for the issue to be assigned to you before starting work. To prevent duplication of effort, submissions for unassigned issues will not be accepted.

**Comment by abhishek818** [comment]
@rickstaa @JJassonn69 can I take this up? You can checkout some of my golang based open source contributions [here](https://github.com/search?q=repo%3Adaytonaio%2Fdaytona+mentions%3Aabhishek818&type=pullrequests&s=created&o=asc).

**Comment by rickstaa** [comment]
> @rickstaa @JJassonn69 can I take this up? You can checkout some of my golang based open source contributions [here](https://github.com/search?q=repo%3Adaytonaio%2Fdaytona+mentions%3Aabhishek818&type=pullrequests&s=created&o=asc).

Hi @abhishek818,

Thank you for your interest in contributing to our open-source community ❤️‍🔥! Unfortunately, this bounty is actually part two of a previous task, which you can find here: https://github.com/livepeer/bounties/issues/49. It was created to break the larger task into smaller parts, and as such, it has already been assigned to someone working on the initial bounty. 

You can check out the implementation progress here: [link](https://github.com/livepeer/grafana-dashboards/pull/1/files/f4164154e7dc4fe8d761ec209636fa489d6da718..4beeb4f5cf38ae2fc9e4b067590b8104649949bd).

We regularly post new bounties, so I'm confident there will be more opportunities for you to contribute soon. Keep an eye out, and we hope to see you involved in future projects 🚀!

**Comment by rickstaa** [comment]
This bounty was completed by @stronk-dev in https://github.com/livepeer/grafana-dashboards/pull/1.
